name: autofix.ci
on:
  pull_request:
    paths:
      - "poetry.lock"
      - "pyproject.toml"
      - "src/backend/**"
env:
  POETRY_VERSION: "1.8.2"

jobs:
  lint:
    name: Run Ruff Check and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: install-pinned/ruff@f5afd2b0fca6556debe3e07025fc90e04fb3c44c
      - run: ruff check --fix-only .
      - run: ruff format .
      - uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a
